name: Enhancement
description: Request a new feature or enhancement.
labels: ["enhancement"]
title: "[ENHANCEMENT]: "
body:
  - type: markdown
    attributes:
      value: |
        Please make sure this feature request is original and has not been removed because of a major flaw/issue.
  
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Give us a description of the feature or enhancement you would like
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
      description: Give us some additional information such as proposed solutions, links, designs, etc.